### ISSUE TITLE
Help with integration with create-react-app

### ISSUE THREAD

**Issue by mikeh2** [GetAmbassador/react-ions#630]
I am unable to get this library to work/integrate with the boilerplate from create-react-app.  I used several different sources to configure webpack for scss modules, but still no luck. 

1.  I am using React 16.3 [despite the warnings, the component seems to behave properly]
2. The resulting dom isn't styled and doesn't match the examples online.

As a starting point, my configuration follows 
https://medium.com/@mzohaib.qc/using-sass-scss-with-react-app-create-react-app-d03072083ef8

this configuration was able to get a non react-ion scss file to work with no changes to the webpack.dev.config file

However if add the following to App.js:

```
import InlineEdit from 'react-ions/lib/components/InlineEdit';
....
<InlineEdit value="test"/>
```
There's still no styling; yet my included App.scss file works fine.  I even tried to import all the react-ions scss files directly; but still nothing.

I also tried the example
`https://github.com/GetAmbassador/reactions-webpack-example`
but the build (npm run build), did not work:

```
ERROR in ./~/react-ions/lib/components/SelectField/style.scss
Module parse failed: /Users/mikeh/home/projects/scratch/reactions-webpack-example/node_modules/react-ions/lib/components/SelectField/style.scss Unexpected character '@' (1:0)
You may need an appropriate loader to handle this file type.
| @import '../../styles/common/colors';
| @import '../../styles/common/screen';
| @import '../../styles/common/mixins';
 @ ./~/react-ions/lib/components/SelectField/SelectField.js 26:13-36
 @ ./~/react-ions/lib/components/SelectField/index.js
 @ ./~/react-ions/lib/components/InlineEdit/InlineEdit.js
 @ ./~/react-ions/lib/components/InlineEdit/index.js
 @ ./app/containers/HomePage/index.js
```
Any help with what needs to be done to get this library to work with create-react-app would be welcomed with open arms.

thanks so much

**Comment by samageloff** [comment]
Hi @mikeh2, thanks for sending this over. Regarding the `reactions-webpack-example`, the command to run the app is actually `npm start`, which should work for you. 

As for the `create-react-app` implementation, I will take a look and get back to you. 

Best, 
Sam

**Comment by samageloff** [comment]
@mikeh2 re: the `create-react-app` issue, the import path is `react-ions/lib/components/InlineEdit`. You have `react-ions/src/components/InlineEdit`. Try that change, and the inline edit should render properly.

**Comment by samageloff** [comment]
@mikeh2, 

Finally getting back to you on this. If you still want to try this out, here are the steps to get the library running in `create-react-app`:

- In your newly created app directory, run `npm run eject`
- Run `npm install sass-loader node-sass --save-dev`

- For development, edit `webpack.config.dev.js` and add the items highlighted in green below:

![image](https://user-images.githubusercontent.com/843090/40504240-bbabfed8-5f5e-11e8-9dc1-4b369dfad9cb.png)

Now you should be able to import any React:ion component, like so: 
`import Button from 'react-ions/lib/Button';`

Let me know if you have any issues here, or if you need the production config as well. 

Best,
Sam
